// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contracting-company/ClientPortal.tsx": () => import("../components/mockups/contracting-company/ClientPortal.tsx"),
  "./components/mockups/contracting-company/EmployeeDashboard.tsx": () => import("../components/mockups/contracting-company/EmployeeDashboard.tsx"),
  "./components/mockups/contracting-company/Homepage.tsx": () => import("../components/mockups/contracting-company/Homepage.tsx"),
  "./components/mockups/contracting-company/Login.tsx": () => import("../components/mockups/contracting-company/Login.tsx")
};
